### PR TITLE
Change the process shutdown strategy.

### PR DESCRIPTION
**Pull request by qpautrat**
We need to be able to shutdown our process gracefully.

My idea is to let the daemon decides how to stop its work.
That is why I removed the `exit` part.
When the signal is caught, we just want to warn the daemon and nothing else.
Then execution flow returns where it was before the signal and should come out the `Dameon::start()` method to finish the script and gracefully exit with a `0` return code.

Of course this means it creates a BC break and need a MAJOR upgrade.

What do you think about it ?

### CODE REVIEW

**Comment by kipit** [comment]
@qpautrat agree (BTW the exit code change we did previously was also a BC break 😬 )

**Comment by qpautrat** [comment]
You are right.

**Comment by kipit** [comment]
Well, I've just thinking about something: what's the purpose of `Worker` (vs `Daemon`)? (cc @remi-san).

**Comment by qpautrat** [comment]
It is a excellente question I already asked myself.

**Review by remi-san — APPROVED** [review]
Oui, c'est une bonne idée

**Comment by remi-san** [comment]
We need to differentiate the `Worker` from the `Daemon` as the worker doesn't do anything specific but manages the signals, and the daemon is there for specific work... it's a way to separate concerns...

For the naming, I can acknowledge this might not be the best of ideas... I can take suggestions

**Pull request closed without merging**
